[server]
host = "0.0.0.0"
port = 3001
max_request_size_mb = 110

[backend]
base_url = "http://127.0.0.1:8080"
timeout_seconds = 300

[webui]
title = "Whisper WebUI"
max_file_size_mb = 100
allowed_extensions = ["wav", "mp3", "m4a", "flac", "ogg", "mp4", "mov", "avi", "mkv"]
default_language = "ja"
default_with_timestamps = true
timeline_update_interval_ms = 200
upload_prompt_text = "音声ファイルをドラッグ&ドロップするか、クリックして選択してください"
upload_success_text = "{filename} を選択しました"
stats_average_processing_time_label = "平均処理時間 (音声1分あたりの文字起こし所要時間)"
stats_average_processing_time_unit = "秒 / 音声1分"

[realtime]
enabled = true
config_dir = "../WhisperRealtimeAPI/config"
backend_ws_url = "ws://127.0.0.1:8081"
connection_timeout_seconds = 10
default_client_type = "browser"
default_client_name = "Chrome"
default_client_version = "130"
default_token_subject = "web-demo"
heartbeat_interval_ms = 30000
